apiVersion: v1
kind: Pod
metadata:
  name: salseando-pod
  namespace: salsa
  labels:
    app: jesusl2
  annotations:
    descripcion: "Este pod es fan Ruben Blades"
    metodo: "accede por medio de tolerations y nodeaffinity"
    owner: "JesusLopez"
    contacto: "jesus.betancourth@correounivalle.edu.com"
spec:
  containers:
    - name: salseando
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "sabor-latino"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - latino
  