apiVersion: v1
kind: Pod
metadata:
  name: rockerito-pod
  namespace: rock
  labels:
    app: bayron1
  annotations:
    descripcion: "Este pod ama el rock y quiere escuchar caifanes"
    metodo: "accede por medio de tolerations"
    owner: "Bayron Jojoa"
    contacto: "bayron.jojoa@correounivalle.edu.com"
spec:
  containers:
    - name: rockeando
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"