apiVersion: v1
kind: Pod
metadata:
  name: electronica-pod
  namespace: techno
  labels:
    app: julianp
  annotations:
    descripcion: "Ponganme una de avicii, preferiblemente For a better day"
    metodo: "accede por medio de tolerations y nodeaffinity"
    owner: "julianpg"
    contacto: "julian.palco@correounivalle.edu.co"
spec:
  containers:
    - name: electrica
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico
  