apiVersion: v1
kind: Pod
metadata:
  name: timbaleropod
  namespace: salsa
  labels:
    app: juand1
spec:
  containers:
    - name: hectorlavo
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - latino