apiVersion: v1
kind: Pod
metadata:
  name: perreo-pod
  namespace: reggaeton
  labels:
    app: alejandro2
  annotations:
    descripcion: "Este pod lo baja hasta el piso"
    metodo: "accede por medio de tolerations y nodeaffinity"
    owner: "Alejandro Muñoz"
    contacto: "munoz.cesar@correounivalle.edu.co"
spec:
  containers:
    - name: ppperreo
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "perreo-intenso"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - urbano
  