apiVersion: v1
kind: Pod
metadata:
  name: perreito-pod
  namespace: reggaeton
  labels:
    app: santiago1
  annotations:
    descripcion: "Este pod es cosa loca!"
    metodo: "accede por medio de tolerations y nodeaffinity"
    owner: "Santiago Ruiz"
    contacto: "santiago.ruiz.cortes@correounivalle.edu.co"
spec:
  containers:
    - name: perreito
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "perreo-intenso"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - urbano
  